---
name: Vendor Dependencies Check
permissions:
  contents: read
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  depscheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
         go-version: '1.18.5'
      - run: bash scripts/gogetcookie.sh
      - run: make depscheck
